from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('sales/', views.sales_page, name='sale'),
    path('sales/add/', views.add_sales_record,
         name='add sales'),
    path('sales/add/reference/', views.add_sales_from_ref,
         name='add_from_ref'),
    path('sales/add/reference/finish/<int:ref>', views.save_sales_to_db,
         name='add_from_ref_finish'),
    path('sale/details/<int:pk>/', views.SaleDetailView.as_view(),
         name='single sale record'),
    path('sale/delete/<int:pk>/', views.delete_sale_record,
         name='delete single sale'),
    path('sale/update/<int:pk>/', views.edit_sale_record,
         name='edit sale record'),
    path('products/', views.product_page, name='product'),
    path('products/add/', views.add_product_record,
         name='add product'),
    path('products/details/<int:pk>/', views.ProductDetailView.as_view(),
         name='product details'),
    path('products/delete/<int:pk>/', views.delete_product_record,
         name='delete product'),
    path('products/update/<int:pk>', views.edit_product_record,
         name='edit sale record'),
    path('shopping/', views.shopping, name='shopping '),
    path('add_to_cart/<int:pk>', views.add_to_cart, name='add to cart'),
    path('remove_from_cart/<int:pk>', views.delete_from_cart,
         name='delete from cart'),
    path('remove_from_check_out/<int:pk>', views.delete_from_cart2,
         name='delete from check out'),
    path('cancel_selection/', views.cancel_selection,
         name='cancel selection'),
    path('reference_code/', views.generate_reference,
         name='generate reference'),
    path('check_out/', views.check_out, name='check out'),
    path('contact/', views.contact_us, name='contact us'),
    path('messages/', views.message, name='messages'),
    path('messages/delete/<int:pk>', views.delete_message,
         name='delete message'),
    # --------------------------------------------------------
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('customer/account/create/', views.customer_creation,
         name='customer creation'),
    path('change_password/', views.ChangePassword.as_view(),
         name='change password'),
    path('password_reset', views.PasswordReset.as_view,
         name='reset password'),
    path('profile/', views.profile, name='profile'),
    path('view_profile/<int:pk>/', views.member_profile,
         name='member profile'),
    path('update_profile/<int:pk>/', views.user_update,
         name='update user'),
    path('add_user/', views.add_user, name='add member'),
    path('delete_profile/<int:pk>/', views.delete_user,
         name='delete member'),


]
