# Generated by Django 3.0.3 on 2020-02-22 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to=smms.models.path_to_images)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=smms.models.path_to_images)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default=('male', 'male'), max_length=10)),
                ('phone', models.PositiveIntegerField()),
                ('rank', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=smms.models.path_to_images)),
                ('state', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
